account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout,logout_then_login
from django.contrib.auth.views import password_change,password_change_done
from django.contrib.auth.views import password_reset,password_reset_done
from django.contrib.auth.views import password_reset_complete,password_reset_confirm
 




urlpatterns = [



	url(r'^register/$', views.register,name='register'), 

	url(r'^images/$', views.dashboard,name='images'), 
	url(r'^people/$', views.dashboard,name='people'), 


	url(r'^$', views.dashboard,name='dashboard'), 

    #url(r'^login$', views.user_login,name='login'),
	url(r'^login/$', login,name='login'), 

	url(r'^logout/$',logout,name='logout'),
	url(r'logout-then-login/$',logout_then_login,name='logout-then-login'),

	#password change
		url(r'^password-change/$',password_change,name='password_change'),
		url(r'^password-change-done/$',password_change_done,name='password_change_done'),
	#Password reset
	url(r'^password-reset/$',password_reset,name='password_reset'),
	url(r'^password-reset-done/$',password_reset_done,name='password_reset_done'),
	url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',password_reset_confirm,name='password_reset_confirm'),
	url(r'^password-reset/complete/$',password_reset_complete,name='password_reset_complete'),



]

bookmarks/urls.py
from django.conf.urls import url ,include
from django.contrib import admin
from django.shortcuts import HttpResponse
from shibli import call

urlpatterns = [
	url(r'^$',call),
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('account.urls')),
    url(r'^social-auth/',include('social_django.urls',namespace='social')),
    url(r'^images/',include('images.urls',namespace ='images')),
]

images/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.views.static import serve

urlpatterns=[
url(r'^create/$',views.image_create,name='create'),
url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.image_detail,name='detail'),
url(r'^like/$',views.image_like,name='like'),
url(r'^$',views.image_list,name='list'),
url(r'^users/$',views.user_list,name='user_list'),
url(r'^users.(?P<username>[-\w]+)/$',views.user_detail)


]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

class Contact(models.Model):
	user_from= models.ForeignKey(User,related_name='rel_from_set')
	user_to = models.ForeignKey(User, related_name='rel_to_set')
	created = models.DateTimeField(auto_now_add=True,db_index=True)

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return '{} follows {}'.format(self.user_from,self.user_to)



User.add_to_class('following',models.ManyToManyField('self',through=Contact,related_name='followers',symmetrical=False))

# Add following field to User dynamically

account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password',widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirm Password',widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ('username','first_name','email')

	def clean_password2(self):
		cd = self.cleaned_data
		if(cd['password']!=cd['password2']):
			raise forms.ValidationError('Password don\'t match.')
		return cd['password2']

account/views.py
from django.shortcuts import render ,render,get_object_or_404
from  django.shortcuts import HttpResponse
from django.contrib.auth import authenticate,login
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm


def user_login(request):
	if(request.method=="POST"):
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			user = authenticate(username=cd['username'],password=cd['password'])
			if user is not None:

				if(user.is_active):
					login(request,user)
					return HttpResponse('Authenticated successfully')
				else:
					return HttpResponse('Disabled Account')
			else:
				return HttpResponse('Invalid login')
	else:
		form = LoginForm()
		return render(request,'account/login.html',{'form':form})
@login_required
def dashboard(request):
	return render(request,'account/dashboard.html',{'section':'dashboard'})

def register(request):
	if request.method=="POST":
		user_form =UserRegistrationForm(request.POST)
		if(user_form.is_valid):
			new_user= user_form.save(commit=False)
			new_user.set_password(user_form.cleaned_data['password'])
			new_user.save()
			return render(request,'account/register_done.html',{'new_user':new_user})
	else:
		user_form = UserRegistrationForm()
	return render(request,'account/register.html',{'user_form':user_form})

@login_required
def user_list(request):
	users = User.objects.filter(is_active=True)
	return render(request,'account/user/list.html',{'section':'people','users':users})

@login_required
def user_detail(request):
	user =get_object_or_404(User,username=username,is_active=True)
	return render(request,'account/user/detail.html',{'section':'people','user':user})

account/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
</head>
<body>
	<div id="header">
		<span class="logo">Bookmarks</span>
		{%if request.user.is_authenticated %}
			<ul class="menu">
				<li{% if section == "dashboard" %} class="selected"{%endif%}>
				<a href="{% url "dashboard" %}"> Dashboard</a>
				</li>

				<li{% if section == "images" %} class="selected"{% endif %}>
				<a href="{%url "images:list" %}" >Images</a>
				</li>
				<li{% if section == "people" %} class="selected"{%endif%}>
				<a href="{%url "people" %}">People</a>
				</li>
			</ul>
		{% endif %}
		<span  class="user">
			{%if request.user.is_authenticated %}
				Hello {{ request.user.first_name}},<a href="{% url "logout" %}">Logout</a>
			{%else%}
				<a href="{url "login"}">Log-in</a>
			{%endif%}

		</span>
	</div>
	<div id="content">
		{% block content %}
		{% endblock %}		
	</div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
		});
    </script>

</body>
</html>